foreground = yes
client     = no
cert       = /root/srtunnel/server.crt
key        = /root/srtunnel/server.key

[ssl-ssh]
accept       = 0.0.0.0:8443
connect      = 127.0.0.1:22
sslVersionMin = TLSv1.2
ciphers      = AES128-GCM-SHA256:AES256-GCM-SHA384
TIMEOUTidle  = 86400
TIMEOUTclose = 86400
TIMEOUTbusy  = 86400
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
socket = l:SO_KEEPALIVE=1
socket = l:SO_RCVBUF=4194304
socket = l:SO_SNDBUF=4194304
socket = r:SO_RCVBUF=4194304
socket = r:SO_SNDBUF=4194304